name: Builds
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/docs.yaml"
      - ".github/workflows/publish.yaml"
      - ".github/workflows/tests.yaml"
      - "*.md"
  pull_request:
    branches:
      - main

jobs:
  cmake:
    # Bionic default: gcc 7, python 3.6
    # Focal default: gcc 9, python 3.8
    # Catalina default: clang 12, python 3.9
    name: CMake ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
